app/src/Entity/TrickImage.php
<?php

namespace App\Entity;

use App\Repository\TrickImageRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: TrickImageRepository::class)]
class TrickImage
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\NotBlank(message: 'Le nom de l\'image est obligatoire')]
    private $name;

    #[ORM\ManyToOne(targetEntity: Trick::class, inversedBy: 'trickImages')]
    private $trick;

    /** @var UploadedFile */
    #[Assert\Image(
        maxSize: 10240000,
        minWidth: 200,
        maxWidth: 1920,
        minHeight: 200,
        maxHeight: 1920,
        mimeTypes: ['image/jpeg', 'image/jpg', 'image/png'],
        mimeTypesMessage: 'Veuillez entrer un fichier valide',
        allowPortrait: false,
        allowPortraitMessage: "L'image doit etre au format paysage"
    )]
    private $file;

    #[ORM\Column(type: 'string', length: 255)]
    private $filename;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getTrick(): ?Trick
    {
        return $this->trick;
    }

    public function setTrick(?Trick $trick): self
    {
        $this->trick = $trick;

        return $this;
    }

    /**
     * @return File|null
     */
    public function getFile(): ?File
    {
        return $this->file;
    }

    /**
     * @param File $file
     */
    public function setFile(File $file): void
    {
        $this->file = $file;
    }

    /**
     * @return string
     */
    public function getPath(): string
    {
//        $params = new ParameterBag();
//        return $params->get('trickImages_directory').'/'.$this->getName();
        return 'uploads/tricks/'.$this->getFilename();
    }

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    public function setFilename(string $filename): self
    {
        $this->filename = $filename;

        return $this;
    }
}

app/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string', length: 255, unique: true)]
    private $username;

    #[ORM\Column(type: 'string', length: 255)]
    private $fullname;

    #[ORM\Column(type: 'boolean')]
    private $isVerified;

    #[ORM\Column(type: 'datetime')]
    private $createdAt;

    #[ORM\Column(type: 'datetime')]
    private $agreedTermsAt;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Trick::class)]
    private $tricks;

    #[ORM\Column(type: 'string', nullable: true)]
    private $registrationToken;

    private $accountMustBeVerifiedBefore;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Message::class)]
    private $messages;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $avatarFilename;


    public function __construct()
    {
        $this->tricks = new ArrayCollection();
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): ?string
    {
        return $this->username;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): ?string
    {
        return $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getFullname(): ?string
    {
        return $this->fullname;
    }

    public function setFullname(?string $fullname): self
    {
        $this->fullname = $fullname;

        return $this;
    }

    public function getIsVerified(): ?bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAgreedTermsAt(): ?\DateTimeInterface
    {
        return $this->agreedTermsAt;
    }

    public function agreeTermes(): self
    {
        $this->agreedTermsAt = new \DateTime();

        return $this;
    }

    /**
     * @return Collection|Trick[]
     */
    public function getTricks(): Collection
    {
        return $this->tricks;
    }

    public function addTrick(Trick $trick): self
    {
        if (!$this->tricks->contains($trick)) {
            $this->tricks[] = $trick;
            $trick->setAuthor($this);
        }

        return $this;
    }

    public function removeTrick(Trick $trick): self
    {
        if ($this->tricks->removeElement($trick)) {
            // set the owning side to null (unless already changed)
            if ($trick->getAuthor() === $this) {
                $trick->setAuthor(null);
            }
        }

        return $this;
    }

    public function getRegistrationToken(): string
    {
        return $this->registrationToken;
    }

    public function setRegistrationToken($registrationToken): self
    {
        $this->registrationToken = $registrationToken;
        return $this;
    }

    public function getAccountMustBeVerifiedBefore(): \DateTimeInterface
    {
        return $this->accountMustBeVerifiedBefore;
    }

    public function setAccountMustBeVerifiedBefore(\DateTimeInterface $accountMustBeVerifiedBefore): self
    {
        $this->accountMustBeVerifiedBefore = $accountMustBeVerifiedBefore;

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setAuthor($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getAuthor() === $this) {
                $message->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getAvatarFilename(): mixed
    {
        return $this->avatarFilename;
    }

    /**
     * @param mixed $avatarFilename
     * @return User
     */
    public function setAvatarFilename(string $avatarFilename): self
    {
        $this->avatarFilename = $avatarFilename;
        return $this;
    }

    /**
     * @return string
     */
    public function getAvatarsPath(): string
    {
        return 'uploads/avatars/'.$this->getAvatarFilename();
    }
}

app/src/Controller/TrickController.php
<?php

namespace App\Controller;

use App\Entity\Message;
use App\Entity\Trick;
use App\Form\MessageType;
use App\Form\Model\EditTrickFormModel;
use App\Form\Trick\EditTrickType;
use App\Form\Trick\TrickType;
use App\Repository\MessageRepository;
use App\Service\ImageService;
use App\Service\Paginator;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

class TrickController extends AbstractController
{
    private EntityManagerInterface $entityManager;
    private SluggerInterface $slugger;
    private ImageService $imageService;
    private Paginator $paginator;
    private RequestStack $requestStack;

    public function __construct(EntityManagerInterface $entityManager, SluggerInterface $slugger, ImageService $imageService, Paginator $paginator, RequestStack $requestStack)
    {
        $this->entityManager = $entityManager;
        $this->slugger = $slugger;
        $this->imageService = $imageService;
        $this->paginator = $paginator;
        $this->requestStack = $requestStack;
    }

//    #[Route('/{category_slug}/{slug}', name: 'trick_show')]
//    public function show(string $slug): Response
//    {
//        $trick = $this->trickRepository->findOneBy(compact('slug'));
//
//        if(!$trick)
//        {
//            throw $this->createNotFoundException("Ce trick n'existe pas");
//        }
//
//        return $this->render('trick/show.html.twig', compact('trick'));
//    }

    #[Route('/{category_slug}/{slug}', name: 'trick_show', methods: ['GET', 'POST'], priority: -1)]
    public function show(Trick $trick, Request $request): Response
    {
        $message = new Message();
        $form = $this->createForm(MessageType::class, $message);

        $form->handleRequest($request);

        $messagesPagination = $this->paginator->paginate(10, $trick->getId());
        [
            $messages,
            $totalPages,
            $currentPage
        ] = $messagesPagination;

        if($form->isSubmitted() && $form->isValid())
        {
            if(!$this->getUser())
            {
                return $this->redirectToRoute('homepage');
            }

            $message->setCreatedAt(new \DateTime('now'));
            $message->setTrick($trick);
            $message->setAuthor($this->getUser());
            $this->entityManager->persist($message);
            $this->entityManager->flush();

            return $this->redirectToRoute('trick_show', ['category_slug' => $trick->getTrickCategory()->getSlug(), 'slug' => $trick->getSlug()]);
        }

        return $this->renderForm('trick/show.html.twig', compact('trick', 'form', 'messages', 'totalPages', 'currentPage'));
    }

    #[Route('/trick/create', name: 'trick_create')]
    #[IsGranted('ROLE_USER', message: 'Vous devez etre connecté pour pouvoir creer un trick')]
    public function create(Request $request): Response
    {
        $trick = new Trick();
        $form = $this->createForm(TrickType::class, $trick);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $trickImages = $trick->getTrickImages();

            foreach($trickImages as $trickImage)
            {
                $this->imageService->moveTrickImageToFinalDirectory($trickImage);
            }

            if($trickImages) $trick->setMainTrickImage($trickImages[0]);
            $trick->setSlug(strtolower($this->slugger->slug($trick->getName())));
            $trick->setCreatedAt(new \DateTime('now'));
            $trick->setAuthor($this->getUser());
            $this->entityManager->persist($trick);
            $this->entityManager->flush();

            $this->addFlash('success', 'Le trick a bien été enregistré');

            return $this->redirectToRoute('homepage');
        }

        return $this->renderForm('trick/create.html.twig', compact('form'));
    }


    #[Route('/trick/{slug}/edit', name: 'trick_edit')]
    public function edit(Trick $trick)
    {
        $this->denyAccessUnlessGranted('CAN_EDIT', $trick, "Vous n'avez pas le droit d'acceder à ce trick");

        $request = $this->requestStack->getCurrentRequest();
        if($request->isXmlHttpRequest())
        {
            return $this->renderEditTemplate($request, $trick);
        }

        // On injecte les données du trick dans le model (DTO)
        $trickModel = EditTrickFormModel::fromTrick($trick);
        // On crée un formulaire de type Edit et on lui associe la classe du DTO
        $form = $this->createForm(EditTrickType::class, $trickModel);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $this->updateTrickFromDto($trick, $trickModel, $form);

            $this->entityManager->flush();
            $this->addFlash('success', 'Le trick a bien été modifié');

            return $this->redirectToRoute('trick_show', ["category_slug" => $trick->getTrickCategory()->getSlug(), "slug" => $trick->getSlug()]);
        }

        return $this->renderForm('trick/edit.html.twig', compact('form', 'trick'));
    }

    #[Route('/trick/{slug}/delete', name: 'trick_delete', methods: ['GET', 'DELETE'])]
    public function delete(Request $request, Trick $trick)
    {
        $this->denyAccessUnlessGranted('CAN_DELETE', $trick, "Vous n'avez pas le droit d'acceder à ce trick");

        $data = json_decode($request->getContent(), true);
//        dd($request->query);
        if($this->isCsrfTokenValid("delete-trick", $data['_token']))
        {
            foreach($trick->getTrickImages() as $trickImage)
            {
                $this->imageService->removeUploadedTrickImage($trickImage);
            }
            $this->entityManager->remove($trick);
            $this->entityManager->flush();

            return $this->json([
                'code' => 200,
                'message' => 'success'
            ], 200);
            //        return $this->redirectToRoute('homepage', [], Response::HTTP_SEE_OTHER);
        }

        return $this->json([
            'code' => 400,
            'message' => 'error'
        ], 400);
    }

    private function updateTrickFromDto(Trick $trick, EditTrickFormModel $trickModel, FormInterface $form){
        $trick->setName($trickModel->name);
        $trick->setDescription($trickModel->description);
        $trick->setTrickCategory($trickModel->trickCategory);
        $trick->setUpdatedAt(new \DateTime('now'));

        $newTrickImagesForm = $form->get('newTrickImages')->getData();
        foreach($newTrickImagesForm as $newTrickImage)
        {
            if($newTrickImage && !$newTrickImage->getId()){
                $trick->addTrickImage($newTrickImage);
                $this->imageService->moveTrickImageToFinalDirectory($newTrickImage);
            }
        }

        $newTrickVideosForm = $form->get('newTrickVideos')->getData();
        foreach($newTrickVideosForm as $newTrickVideo)
        {
            if($newTrickVideo){
                $trick->addTrickVideo($newTrickVideo);
            }
        }
    }

    private function renderEditTemplate(Request $request, Trick $trick)
    {
        if($request->getContent() === 'image'){
            return $this->json([
                '_template' => $this->render('trick/_edit_imageTrick.html.twig', compact('trick')),
            ]);
        }
        elseif($request->getContent() === 'video')
        {
            return $this->json([
                '_template' => $this->render('trick/_edit_videoTrick.html.twig', compact('trick')),
            ]);
        }
    }
}

app/templates/trick/_editForm.html.twig

{{ form_start(form) }}
    {{ form_row(form.name) }}
    {{ form_row(form.description) }}
    {{ form_row(form.trickCategory) }}

    <h4>Images</h4>
    <ul
            class="pictures"
            data-index="{{ form.newTrickImages|length > 0 ? form.newTrickImages|last.vars.name + 1 : 0 }}"
            data-prototype="{{ form_widget(form.newTrickImages.vars.prototype)|e('html_attr') }}"
    >
        <button type="button" class="add_item_link" data-collection-holder-class="pictures">Ajouter une image</button>
        {% for image in form.newTrickImages %}
            {% if not image.name %}
                <li class="item">{{ form_row(image.name) }}</li>
                <li class="item">{{ form_row(image.file) }}</li>
                {{ form_errors(image) }}
            {% endif %}
        {% endfor %}
    </ul>

    <h4>Videos</h4>
    <ul
            class="videos"
            data-index="{{ form.newTrickVideos|length > 0 ? form.newTrickVideos|last.vars.name + 1 : 0 }}"
            data-prototype="{{ form_widget(form.newTrickVideos.vars.prototype)|e('html_attr') }}"
    >
        <button type="button" class="add_item_link" data-collection-holder-class="videos">Ajouter une video</button>
        {% for video in form.newTrickVideos %}
            <li class="item">{{ form_row(video.name) }}</li>
            <li class="item">{{ form_row(video.url) }}</li>
            <li class="item">{{ form_row(video.provider) }}</li>
        {% endfor %}
    </ul>

    <button class="btn btn-primary">
        <i class="fa fa-save"></i>
        Enregistrer les modifications
    </button>
{{ form_end(form) }}





{#    <div class="row">#}
{#        {% for trickImage in trick.trickImages %}#}
{#            <div class="col-lg-3 mb-sm-2">#}
{#                <img src="{{ asset(trickImage.path) }}" class="img-thumbnail rounded" alt="{{ trickImage.name }}">#}
{#                <a href="{{ path('trick_image-delete', {'slug': trick.slug, 'id': trickImage .id }) }}" data-delete data-token="{{ csrf_token('delete-image') }}"><i class="fa fa-trash"></i> Supprimer</a>#}
{#            </div>#}
{#        {% endfor %}#}
{#    </div>#}
{#    {{ form_errors(form.trickImages) }}#}

{#{{ form_end(form , {render_rest: false}) }}#}

app/templates/trick/_edit_imageTrick.html.twig
<h4>Gestion des Images</h4>

<div class="row">
    {% for trickImage in trick.trickImages %}
        <div id="trickImage-{{ trickImage.id }}" class="col-lg-3 mb-sm-2 d-flex justify-content-between align-items-center">
            <div>
                <img src="{{ asset(trickImage.path) }}" class="img-thumbnail rounded" alt="{{ trickImage.name }}">
                <div class="d-flex justify-content-between align-items-center">
                    <div>
                        <label for="mainPicture">Principale</label>
                        <input type="radio" name="mainPicture" class="js-mainPicture" data-mainPicture="{{ path('trick_setTricksMainPicture', {'slug': trick.slug, 'id': trickImage .id })}}" value="{{ trickImage.id }}">
                    </div>
                    <a href="{{ path('trick_image-delete', {'slug': trick.slug, 'id': trickImage .id }) }}" data-delete data-token="{{ csrf_token('delete-image') }}"><i class="fa fa-trash"></i> Supprimer</a>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

app/templates/trick/_list.html.twig
{% for trick in tricks %}
    <div class="col-12 col-md-6 col-lg-3 pt-5">
        {% include "trick/_trick_card.html.twig" %}
    </div>
{% endfor %}

app/templates/trick/_trick_card.html.twig

<div class="card rounded box js-trick-card" id="trick-{{ trick.slug }}">

    {% if trick.mainTrickImage is null %}
        <img src="{{ asset("uploads/snowboard-default.jpg") }}" class="img-fluid box-img-top card-img-top rounded-top" alt="Image d'un trick par defaut">
    {% else %}
        {% for trickImage in trick.trickImages %}
            {% if trickImage.id == trick.mainTrickImage.id %}
                <img src="{{ asset(trickImage.path) }}" class="box-img-top card-img-top rounded-top" alt="{{ trickImage.name }}">
            {% endif %}
        {% endfor %}
    {% endif %}
        <div class="card-body rounded">
            <div class="row d-flex justify-content-between">
                <div class="col-xl-9">
                    <h4 class="card-title"><a href="{{ path('trick_show', {'category_slug': trick.trickCategory.slug, 'slug': trick.slug}) }}">{{ trick.name }}</a></h4>
                    <h6 class="card-subtitle mb-2 text-muted">{{ trick.trickCategory.name }}</h6>
                </div>

                {% if is_granted('ROLE_ADMIN') or trick.author == app.user %}
                    <div class="col-xl-3 d-sm-flex flex-xl-column">
                        <a class="fs-4 m-2" href="{{ path('trick_edit', {'slug': trick.slug }) }}"><i class="fa fa-edit"></i></a>
                        <a class="fs-4 m-2 js-deleteTrick" href="{{ path('trick_delete', {'slug': trick.slug}) }}" data-deleteTrick data-token="{{ csrf_token('delete-trick') }}"><i class="fa fa-trash"></i></a>
{#                        <button class="fs-4 m-2" id="js-editTrick" data-slug="{{ trick.slug }}"><i class="fa fa-edit"></i></button>#}
{#                        <button class="fs-4 m-2" id="js-deleteTrick" data-slug="{{ trick.slug }}" data-deleteTrick data-token="{{ csrf_token('delete-trick') }}"><i class="fa fa-trash"></i></button>#}
                        {#                    <a class="fs-4 m-2" href="{{ path('trick_delete', {'slug': trick.slug, 'csrf_token': 'remove' }) }}"><i class="fa fa-trash"></i></a>#}
                    </div>
                {% endif %}
             </div>
        </div>
</div>

{#                        <a class="fs-4 m-2" href="{{ path('trick_edit', {'slug': trick.slug }) }}"><i class="fa fa-edit"></i></a>#}
{#                        <a class="fs-4 m-2 " id="js-deleteTrick" href="{{ path('trick_delete', {'slug': trick.slug}) }}" data-deleteTrick data-token="{{ csrf_token('delete-trick') }}"><i class="fa fa-trash"></i></a>#}

app/templates/trick/mainTrickImage.html.twig

{% set mainImageTrickId = trick.mainTrickImage.id %}
{% for trickImage in trick.trickImages %}
    {% if trickImage.id == mainImageTrickId %}
        <img src="{{ asset(trickImage.path) }}" class="img-fluid card-img-top rounded-top" alt="{{ trickImage.name }}">
    {% elseif mainImageTrickId is null%}
        <img src="{{ asset(trickImage.path) }}" class="card-img-top rounded-top" alt="Image d'un trick par defaut">
    {% endif %}
{% endfor %}

app/templates/trick/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ trick.name }}{% endblock %}

{% block body %}

    {% set currentPath = path(app.request.attributes.get('_route'),
        app.request.attributes.get('_route_params')) %}

    <section class="container rounded border border-2 my-5 p-0">
        {% if trick.mainTrickImage is null %}
            <img src="{{ asset("uploads/snowboard-default.jpg") }}" class="card-img-top rounded-top" alt="Image d'un trick par defaut">
        {% else %}
            {% for trickImage in trick.trickImages %}
                {% if trickImage.id == trick.mainTrickImage.id %}
                    <img src="{{ asset(trickImage.path) }}" class="img-fluid rounded-top" alt="{{ trickImage.name }}">
                {% endif %}
            {% endfor %}
        {% endif %}

        <div class="row m-5">
            <div class="col-lg-6">
                <div class="row">
                <h3 class="media-title">Videos</h3>
                </div>
                <div class="row">
                    {% for trickVideo in trick.trickVideos %}
                        <div class="col-lg-4 mb-sm-2">
                            <div class="ratio ratio-16x9">
                                <iframe width="560" height="315" src="{{ trickVideo.url }}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>

            <div class="col-lg-6">
                <div class="row">
                    <h3 class="media-title">Images</h3>
                </div>
                <div class="row">

                    {% for trickImage in trick.trickImages %}
                        <div class="col-lg-4 mb-sm-2 d-flex ">
                            <img src="{{ asset(trickImage.path) }}" class="img-thumbnail rounded" alt="{{ trickImage.name }}">
                        </div>
                    {% endfor %}

                </div>
            </div>
        </div>
        <div class="row p-5">
            <h2>{{ trick.name }}</h2>
            <p><small>Crée le {{ trick.createdAt | date('d/m/Y H:i') }} Par: </small><strong>{{ trick.author.username }}</strong></p>
            <p class="mx-auto"><span class="badge bg-info">{{ trick.trickCategory.name }}</span></p>
            <p class="lead">{{ trick.description }}</p>
        </div>
    </section>

    <section class="container">
        <h2>Espace discussion: </h2>

        {% if app.user %}
            <div>
                {{ form_start(form) }}
                {{ form_row(form.content) }}
                <button type="submit" class="btn btn-success">Envoyer</button>
                {{ form_end(form) }}
            </div>
        {% endif %}


        <div class="mt-5">

        {% if messages|length > 0 %}
        {% for message in messages %}
            <div class="card-body p-4">
                <div class="d-flex flex-start">
                    <img
                            class="rounded-circle shadow-1-strong me-3"
                            src="{{ asset(message.author.avatarsPath) }}"
                            alt="avatar"
                            width="60"
                            height="60"
                    />
                    <div>
                        <h6 class="fw-bold mb-1">{{ message.author.username }}</h6>
                        <div class="d-flex align-items-center mb-3">
                            <p class="mb-0">
                                Le <small>{{ message.createdAt | date('d/m/Y à H:i') }}</small>
                            </p>
                        </div>
                        <p class="mb-0">
                            {{ message.content }}
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <hr class="my-0"/>
        {% endfor %}
        <div class="my-5">
            {#            {{ app.request.query.get('page') }}#}
            <ul class="pagination pagination-lg justify-content-center">
                <li class="page-item {{ currentPage == 1 ? 'disabled' : '' }}">
                    <a class="page-link" href="{{ path('trick_show', {'category_slug': trick.trickCategory.slug, 'slug': trick.slug}) }}?page={{ currentPage - 1 }}">&laquo;</a>
                </li>
                {% for pageNumber in 1..totalPages %}
                    <li class="page-item {{ currentPage == pageNumber ? 'active' : ''}}">
                        <a class="page-link" href="{{ path('trick_show', {'category_slug': trick.trickCategory.slug, 'slug': trick.slug}) }}?page={{ pageNumber }}">{{ pageNumber }}</a>
                    </li>
                {% endfor %}
                <li class="page-item  {{ currentPage == totalPages ? 'disabled' : '' }}">
                    <a class="page-link" href="{{ path('trick_show', {'category_slug': trick.trickCategory.slug, 'slug': trick.slug}) }}?page={{ currentPage + 1 }}">&raquo;</a>
                </li>
            </ul>
        </div>
        {% else %}
        <p>Pas de messages à afficher...</p>
        {% endif %}
    </section>
{% endblock %}